name: 'Install and authenticate SFDX Dev Hub'
description: 'Will install DX, then authenticate to Dev Hub environment'

inputs:
  jwt-signing-key:
    description: 'Private key used to sign JSON web token. This is available in a repository secret and should be passed to this action from the workflow'
  consumer-key:
    description: 'Consumer key (client id) of the Continuous Integration connected app set up in the Dev Hub. Held in a repository secret'
    required: true
  dev-hub-username:
    description: 'Username of the Continuous Integration user in the Dev Hub. Held in a repository secret'
    required: true
  dev-hub-alias:
    description: 'Optional to assign a specific alias to the Dev Hub org'
    required: false
    default: 'devhub'

runs:
  using: "composite"
  steps:

    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli --global
      shell: bash

    # Creates a file with JWT signing key used for authentication
    - name: Authenticate and set default DevHub
      run: |
        echo "${{ inputs.jwt-signing-key }}" > server.key
        sfdx force:auth:jwt:grant --clientid ${{ inputs.consumer-key }} --jwtkeyfile server.key --username ${{ inputs.dev-hub-username }} --setdefaultdevhubusername -a ${{ inputs.dev-hub-alias }}
      shell: bash