# Authenticates to packaging org and deploys contents of the fs-core folder
# All local tests in org are run during deployment

name: Deploy to Packaging Org

# Run on demand (typically expect to run from master)
on:
  workflow_dispatch:

env:
  JWT_SIGNING_KEY:            ${{ secrets.JWT_SIGNING_KEY }}
  DEV_HUB_CONSUMER_KEY:       ${{ secrets.ISV_DEV_HUB_CONSUMER_KEY }}
  DEV_HUB_USERNAME:           ${{ secrets.ISV_DEV_HUB_USERNAME }}
  PACKAGING_ORG_CONSUMER_KEY: ${{ secrets.PACKAGING_ORG_CONSUMER_KEY }}
  PACKAGING_ORG_USERNAME:     ${{ secrets.PACKAGING_ORG_USERNAME }}

jobs:
  deploy-to-packaging:
    runs-on: ubuntu-latest
    steps:

    # Checkout branch so we have source code in working directory
    - name: 'Checkout source code'
      uses: actions/checkout@v2
    
    # Install currently supported node version
    - name: Install node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    # Call an action (from scripts subdirectory) to install DX and authenticate to the dev hub
    - name: Install DX
      uses: ./.github/workflows/scripts/install-and-authenticate-dx
      with:
        jwt-signing-key:  $JWT_SIGNING_KEY
        consumer-key:     $DEV_HUB_CONSUMER_KEY
        dev-hub-username: $DEV_HUB_USERNAME

    - name: Authenticate to Packaging Org
      run: |
        sfdx force:auth:jwt:grant --clientid $PACKAGING_ORG_CONSUMER_KEY --jwtkeyfile server.key -r https://login.salesforce.com --username $PACKAGING_ORG_USERNAME -a "packagingOrg"

    # RunLocalTests is the default for production but included here just in case
    - name: Deploy Core Folder Metadata and Run Tests
      run: |
        sfdx force:source:deploy -u packagingOrg -p fs-core -l RunLocalTests
